### ISSUE TITLE
Look good

### ISSUE THREAD

**Issue by b-mi** [ZviRosenfeld/GeneticAlgorithmEngine#7]
Is this library tested and used in real?

**Comment by ZviRosenfeld** [comment]
Thank you for your interest!

As part of the development of this library, I've created the following two projects:
- [GUI](https://github.com/ZviRosenfeld/GeneticAlgorithmEngine/tree/master/GUI): This project uses the library to solve a very simple problem (finding a vector with the greatest sum). The purpose of this project was to test that the basic different pieces of the library are working fine.
- [TravellingSalesman](https://github.com/ZviRosenfeld/GeneticAlgorithmEngine/tree/master/TravellingSalesman): Uses the library to solve the travelling salesman problem. My main intention in writing this project was to provide people with an example of how to use the library.

Other than this, I'm not sure.

**Comment by b-mi** [comment]
Thanks for the reply. I am almost interested in the real use in terms of the quality of the library, whether it has been tested for functionality and does not contain any basic errors. I ask because I like the way its interface looks to me and I consider trying it.

Next, in terms of further development of this library - do you have any plans?

**Comment by ZviRosenfeld** [comment]
Regrading the library quality, the project contains _a lot_ of unit and integration tests, so I'm fairly certain that the basics are working without bugs.

I have no specific plans regarding future development. Is there anything that you think is missing?

**Comment by b-mi** [comment]
Thanks for the reply. As far as development is concerned, I had in mind mainly improvements against premature convergence.

**Comment by ZviRosenfeld** [comment]
Did you have any specific technique in mind?
